In [1]:
import tensorflow

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv(r"C:\Users\iamha\Downloads\Churn_Modelling.csv")
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
dataset.drop(columns=['RowNumber', 'CustomerId', 'Surname', 'Geography', 'Gender'], inplace=True)

In [5]:
dataset.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0

In [6]:
dataset.isnull().sum()

CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
input_data = dataset.iloc[:, :-1]
output_data = dataset.iloc[:, -1]

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
ss = StandardScaler()

In [10]:
input_data = pd.DataFrame(ss.fit_transform(input_data), columns=input_data.columns)

In [11]:
input_data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-0.440036,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,-1.536794,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.501521,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,2.063884,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276

In [12]:
input_data.shape

(10000, 8)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=10)

In [15]:
x_train.shape

(8000, 8)

# ANN

In [16]:
from keras.layers import Dense, BatchNormalization, Dropout
from keras.models import Sequential
from keras.callbacks import EarlyStopping
from keras.regularizers import L2

In [17]:
ann = Sequential()

## Regularization, Batch Normalization & Dropout Layer

In [18]:
ann.add(Dense(6, input_dim=8, activation="relu", kernel_regularizer=L2(l2=0.01)))
# ann.add(Dropout(0.5))
# ann.add(BatchNormalization())
ann.add(Dense(5, activation="relu", kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(4, activation="relu", kernel_regularizer=L2(l2=0.01)))
# ann.add(Dropout(0.5))
# ann.add(BatchNormalization())
ann.add(Dense(3, activation="relu", kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(2, activation="relu", kernel_regularizer=L2(l2=0.01)))
ann.add(Dropout(0.3))
# ann.add(BatchNormalization())
ann.add(Dense(1, activation="sigmoid"))

c:\Users\iamha\anaconda3\envs\tf-jupyter\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
ann.fit(x_train, y_train, batch_size=100, epochs=50, validation_data=(x_test, y_test), callbacks=EarlyStopping())

Epoch 1/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8056 - loss: 0.8579 - val_accuracy: 0.7890 - val_loss: 0.7722
Epoch 2/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7950 - loss: 0.7469 - val_accuracy: 0.7890 - val_loss: 0.6697
Epoch 3/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8023 - loss: 0.6605 - val_accuracy: 0.7890 - val_loss: 0.6139
Epoch 4/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8047 - loss: 0.6248 - val_accuracy: 0.7890 - val_loss: 0.5843
Epoch 5/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7998 - loss: 0.5976 - val_accuracy: 0.7890 - val_loss: 0.5630
Epoch 6/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7940 - loss: 0.5912 - val_accuracy: 0.7890 - val_loss: 0.5466
Epoch 7/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8032 - loss: 0.5659 - val_accuracy: 0.7890 - val_loss: 0.5389
Epoch 8/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7965 - loss: 0.5587 - val_accuracy: 0.7890 - val_loss: 0.5269
Epoch 9/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8030 - loss: 0.5456 - val_accuracy: 0.7890 - val_loss: 0.5232
Epoch 10/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7969 - loss: 0.5376 - val_accuracy: 0.7890 - val_loss: 0.5160
Epoch 11/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7980 - loss: 0.5332 - val_accuracy: 0.7890 - val_loss: 0.5144
Epoch 12/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7935 - loss: 0.5331 - val_accuracy: 0.7890 - val_loss: 0.5114
Epoch 13/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8015 - loss: 0.5214 - val_accuracy: 0.7890 - val_loss: 0.5091
Epoch 14/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8062 - loss: 0.5137 - val_accuracy: 0.7890 - val_loss: 0.5087
Epoch 15/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8044 - loss: 0.5149 - val_accuracy: 0.7890 - val_loss: 0.5076
Epoch 16/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.5168 - val_accuracy: 0.7890 - val_loss: 0.5050
Epoch 17/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7991 - loss: 0.5119 - val_accuracy: 0.7890 - val_loss: 0.5056

In [21]:
prd = ann.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [22]:
prd_data = []
for i in prd:
    if i[0] > 0.5:
        prd_data.append(1)
    else:
        prd_data.append(0)

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
accuracy_score(y_test, prd_data)

0.789

In [25]:
prd1 = ann.predict(x_train)
prd1_data = []
for i in prd1:
    if i[0] > 0.5:
        prd1_data.append(1)
    else:
        prd1_data.append(0)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step

In [26]:
accuracy_score(y_train, prd1_data)

0.798125

## Overfitting & Early Stopping

In [27]:
import matplotlib.pyplot as plt

In [28]:
train_accuracy = ann.history.history['accuracy']
test_accuracy = ann.history.history['val_accuracy']

In [29]:
len(test_accuracy)

17

In [30]:
# plt.plot([i for i in range(1,22)], train_accuracy)
# plt.plot([i for i in range(1,22)], test_accuracy, c='red')

# CNN

In [31]:
from keras.layers import Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator #type:ignore
cnn = Sequential()

In [32]:
cnn.add(Conv2D(32, (3,3), input_shape=(64,64,3),activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2,2)))
cnn.add(Conv2D(32, (3,3),activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2,2)))
cnn.add(Flatten())

c:\Users\iamha\anaconda3\envs\tf-jupyter\lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [33]:
cnn.add(Dense(64, activation='relu'))
cnn.add(Dense(32, activation='relu'))
cnn.add(Dense(16, activation='relu'))
cnn.add(Dense(8, activation='relu'))
cnn.add(Dense(4, activation='relu'))
cnn.add(Dense(1, activation='sigmoid'))

In [34]:
cnn.compile(loss='binary_crossentropy', optimizer='adam')

In [35]:
# train_datagen = ImageDataGenerator(
#         rescale=1./255,
#         shear_range=0.2,
#         zoom_range=0.2,
#         horizontal_flip=True)

# test_datagen = ImageDataGenerator(rescale=1./255)

# train_generator = train_datagen.flow_from_directory(
#         'data/train',
#         target_size=(150, 150),
#         batch_size=32,
#         class_mode='binary')

# test_generator = test_datagen.flow_from_directory(
#         'data/validation',
#         target_size=(150, 150),
#         batch_size=32,
#         class_mode='binary')

# cnn.fit_generator(
#         train_generator,
#         steps_per_epoch=2000,
#         epochs=50,
#         validation_data=test_generator
#         )

In [36]:
# from keras.preprocessing import image
# import numpy as np
# img = image.load_img()
# img = image.img_to_array(img)
# img = np.expand_dims(img, axis=0)

In [37]:
# prd = cnn.predict(img)

In [38]:
# if prd[0][0] < 0.5:
#     print()
# else:
#     print()